"""Core functionality for semantic PCA analysis."""

from .parsing import parse_items
from .embeddings import load_model, embed_items, compute_similarity
from .dimensionality_reduction import (
    DimensionalityReducer,
    ReductionResult,
    UMAPReducer,
    TSNEReducer,
    PCAReducer,
    IsomapReducer,
    SpectralReducer,
    MDSReducer,
    get_reducer,
    reduce_dimensions,
    compare_methods,
    list_available_methods,
    load_dr_config,
    CORE_METHODS,
)
from .analysis import (
    parallel_analysis,
    pca_with_rotation,
    assign_primary,
    mcdonald_omega_from_loadings,
    human_factor_loadings,
    congruence_matrix,
    broken_stick_k,
    elbow_k,
    ppca_bic_k,
    select_k_non_circular,
    rv_coefficient,
    run_kmeans,
    run_spectral,
)
from .umap_hdbscan import umap_hdbscan_auto, umap_reduce
from .utils import ensure_dir
from .clustering import (
    ClusteringStrategy,
    ClusteringResult,
    KMeansConsensusStrategy,
    HDBSCANStrategy,
    validate_n_clusters,
    calculate_cluster_stability,
    analyze_factor_composition_stability,
    validate_consensus_clustering,
    create_consensus_clustering,
    save_consensus_to_model_specs,
    plot_stability_results,
    plot_consensus_model,
)

__all__ = [
    "parse_items",
    "load_model",
    "embed_items",
    "compute_similarity",
    # Dimensionality Reduction
    "DimensionalityReducer",
    "ReductionResult",
    "UMAPReducer",
    "TSNEReducer",
    "PCAReducer",
    "IsomapReducer",
    "SpectralReducer",
    "MDSReducer",
    "get_reducer",
    "reduce_dimensions",
    "compare_methods",
    "list_available_methods",
    "load_dr_config",
    "CORE_METHODS",
    # Analysis
    "parallel_analysis",
    "pca_with_rotation",
    "assign_primary",
    "mcdonald_omega_from_loadings",
    "human_factor_loadings",
    "congruence_matrix",
    "broken_stick_k",
    "elbow_k",
    "ppca_bic_k",
    "select_k_non_circular",
    "rv_coefficient",
    "run_kmeans",
    "run_spectral",
    "umap_hdbscan_auto",
    "umap_reduce",
    "ensure_dir",
    # Clustering
    "ClusteringStrategy",
    "ClusteringResult",
    "KMeansConsensusStrategy",
    "HDBSCANStrategy",
    "validate_n_clusters",
    "calculate_cluster_stability",
    "analyze_factor_composition_stability",
    "validate_consensus_clustering",
    "create_consensus_clustering",
    "save_consensus_to_model_specs",
    "plot_stability_results",
    "plot_consensus_model",
]

